### PR TITLE
Fix for java RSA base 64 function

### PR DESCRIPTION
**Pull request by ghbutton**

### CODE REVIEW

**Comment by pke** [comment]
That's a fix for the RSA not SHA function isn't it? I'll review it later. 

Would be nice to have some detox tests to go with it to verify. But I know it's hard to setup.

**Comment by ghbutton** [comment]
This is the test I added: https://github.com/ghbutton/react-native-simple-crypto-test/blob/master/App.tsx#L160

**Comment by ghbutton** [comment]
@pke ^^

**Comment by pke** [comment]
I can't review that. @pedrouid is set as reviewer

**Pull request merged**
