### PR TITLE
Internal upgrade

### PR DESCRIPTION
**Pull request by ghbutton**
Use base64 for internal representation instead of UTF8 so that we can represent any types of data, not just UTF8 data. (for example files)

### CODE REVIEW

**Comment by pedrouid** [comment]
Hi @ghbutton, I'm no longer maintaining this library. Would you like to maintain it?

**Comment by ghbutton** [comment]
Yea I can, I dont know a ton about android but it is probably better than no one maintaining it

**Comment by pedrouid** [comment]
Alright, let's work on a transition process.

1. I will merge this PR
2. You can delete your own fork
3. I transfer you this fork
4. I give you NPM admin right

**Comment by ghbutton** [comment]
Ok cool

**Comment by pedrouid** [comment]
Started transfer

**Comment by ghbutton** [comment]
Thanks

**Comment by ghbutton** [comment]
Any word on this?

**Comment by pedrouid** [comment]
I’ve initiated the transfer request already, you need to accept it (possibly on your email)

**Comment by ghbutton** [comment]
My apologies could you initiate it one more time? (I failed to accept in time)

**Comment by pedrouid** [comment]
I've initiated a new transfer, check your email for any notifications.

Please be aware that it may conflict with already existing fork of this fork, so I'd recommend you delete it first before accepting it.

Finally once the transfer is completed, give me your NPM username so I can transfer the publishing rights too.

**Comment by ghbutton** [comment]
Thank you, got it transferred. My NPM username is ghbutton

**Comment by pedrouid** [comment]
Invite sent, once accepted I will remove myself

**Comment by pedrouid** [comment]
Actually I can remove prior to accepting.

Congrats! The package is yours 🎉

**Comment by pedrouid** [comment]
You should also update the package.json homepage and repository links so that they are updated to your repo before publishing

**Comment by ghbutton** [comment]
Haha thanks, I will try to take care of it

**Comment by ghbutton** [comment]
Hmm, I am not able to publish to npm yet, do you think it will take some time for those permissions to transfer over?

**Comment by pedrouid** [comment]
there might be because even though I remove myself from the package I can still access the settings but the UI doesn't display my name under maintainers anymore

You could also contact NPM support, I've dealt with them before and they are very helpful

https://www.npmjs.com/support

**Comment by ghbutton** [comment]
I just double checked and was able to publish, thank you

**Pull request merged**
